# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 583)
        MainWindow.setStyleSheet("background-color:#356f8c;\n"
"color:white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.note_text = QtWidgets.QTextEdit(self.centralwidget)
        self.note_text.setGeometry(QtCore.QRect(10, 50, 541, 501))
        self.note_text.setObjectName("note_text")
        self.note_title = QtWidgets.QLineEdit(self.centralwidget)
        self.note_title.setGeometry(QtCore.QRect(10, 10, 541, 20))
        self.note_title.setObjectName("note_title")
        self.new_note_btn = QtWidgets.QPushButton(self.centralwidget)
        self.new_note_btn.setGeometry(QtCore.QRect(580, 10, 201, 23))
        self.new_note_btn.setStyleSheet("background-color:#6396b0;\n"
"border: 2px solid white;\n"
"")
        self.new_note_btn.setObjectName("new_note_btn")
        self.delete_note_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_note_btn.setGeometry(QtCore.QRect(560, 490, 251, 23))
        self.delete_note_btn.setStyleSheet("background-color:#6396b0;\n"
"border: 2px solid white;\n"
"")
        self.delete_note_btn.setObjectName("delete_note_btn")
        self.save_note_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_note_btn.setGeometry(QtCore.QRect(560, 520, 251, 23))
        self.save_note_btn.setStyleSheet("background-color:#6396b0;\n"
"border: 2px solid white;\n"
"")
        self.save_note_btn.setObjectName("save_note_btn")
        self.note_list = QtWidgets.QListWidget(self.centralwidget)
        self.note_list.setGeometry(QtCore.QRect(580, 50, 201, 192))
        self.note_list.setObjectName("note_list")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(580, 250, 191, 16))
        self.label.setObjectName("label")
        self.teg_list = QtWidgets.QListWidget(self.centralwidget)
        self.teg_list.setGeometry(QtCore.QRect(580, 270, 201, 101))
        self.teg_list.setObjectName("teg_list")
        self.add_teg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_teg_btn.setGeometry(QtCore.QRect(560, 430, 251, 23))
        self.add_teg_btn.setStyleSheet("background-color:#6396b0;\n"
"border: 2px solid white;\n"
"")
        self.add_teg_btn.setObjectName("add_teg_btn")
        self.delete_teg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_teg_btn.setGeometry(QtCore.QRect(560, 460, 251, 23))
        self.delete_teg_btn.setStyleSheet("background-color:#6396b0;\n"
"border: 2px solid white;\n"
"")
        self.delete_teg_btn.setObjectName("delete_teg_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.new_note_btn.setText(_translate("MainWindow", "Нова замітка"))
        self.delete_note_btn.setText(_translate("MainWindow", "Видалити"))
        self.save_note_btn.setText(_translate("MainWindow", "Зберегти"))
        self.label.setText(_translate("MainWindow", "Теги"))
        self.add_teg_btn.setText(_translate("MainWindow", "Додати тег"))
        self.delete_teg_btn.setText(_translate("MainWindow", "Видалити тег"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
